/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as AuthenticatedLiveIdRouteImport } from './routes/_authenticated/live.$id'
import { Route as AuthenticatedPacksIdRouteImport } from './routes/_authenticated/packs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLiveIdRoute = AuthenticatedLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacksIdRoute = AuthenticatedPacksIdRouteImport.update({
  id: '/packs/$id',
  path: '/packs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/play/$code': typeof PlayCodeRoute
  '/live/$id': typeof AuthenticatedLiveIdRoute
  '/packs/$id': typeof AuthenticatedPacksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/play/$code': typeof PlayCodeRoute
  '/live/$id': typeof AuthenticatedLiveIdRoute
  '/packs/$id': typeof AuthenticatedPacksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/play/$code': typeof PlayCodeRoute
  '/_authenticated/live/$id': typeof AuthenticatedLiveIdRoute
  '/_authenticated/packs/$id': typeof AuthenticatedPacksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/teacher' | '/play/$code' | '/live/$id' | '/packs/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/teacher' | '/play/$code' | '/live/$id' | '/packs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/teacher'
    | '/play/$code'
    | '/_authenticated/live/$id'
    | '/_authenticated/packs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/live/$id': {
      id: '/_authenticated/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof AuthenticatedLiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs/$id': {
      id: '/_authenticated/packs/$id'
      path: '/packs/$id'
      fullPath: '/packs/$id'
      preLoaderRoute: typeof AuthenticatedPacksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedLiveIdRoute: typeof AuthenticatedLiveIdRoute
  AuthenticatedPacksIdRoute: typeof AuthenticatedPacksIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedLiveIdRoute: AuthenticatedLiveIdRoute,
  AuthenticatedPacksIdRoute: AuthenticatedPacksIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
